apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hackers-api
  labels:
    app: hackers-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hackers-api 